export const commonActionTypes = {
    SET_SITE_LOGO : 'SET_SITE_LOGO',
    SET_LOGO_SUBTEXT : 'SET_LOGO_SUBTEXT',
    SET_MAIN_IMAGE_URL : 'SET_MAIN_IMAGE_URL',
    SET_MAIN_CONTENT : 'SET_MAIN_CONTENT',
    SET_ADDRESS : 'SET_ADDRESS',
    SET_EMAIL : 'SET_EMAIL',
    SET_CONTACT_NO : 'SET_CONTACT_NO',
}